# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application with PyInstaller

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: debian-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller colorama
        pip install -r requirements.txt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build with PyInstaller
      run: |
        pyinstaller --versioninfo=pyinstaller.spec
